name: MkDocs Deploy
on:
  push:
    branches:
      - main

env:
  FUSION_VERSION: 0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==8.2.13
      - run: pip install mike==1.1.2
      - run: git config user.name fusiondoc
      - run: git config user.email fusiondoc@example.com
      - run: mike deploy $FUSION_VERSION latest -u -b gh-pages -p
